### PR TITLE
Add feature/mining_ores

### PR DESCRIPTION
**Pull request by Kanf**

### CODE REVIEW

**Comment by MarvinVomberg** [comment]
Thanks for your work!
Could you add some pictures so everybody knows what we are dealing with?
At least me would love to see it!

**Comment by Arkensor** [comment]
@Kanf what is the progress on the config as items? As far as I remember you wanted to see if you can get that sorted? If not let us know so someone else can handle that.

**Comment by Kanf** [comment]
obraz
obraz



> 

Done :)

**Comment by Kanf** [comment]
> @Kanf what is the progress on the config as items? As far as I remember you wanted to see if you can get that sorted? If not let us know so someone else can handle that.
I have been adding some components to prefabs, but I could use a short tutorial how to configure them

**Comment by Kanf** [comment]
obraz
I have updated prefabs so that items are now usable

**Review by Arkensor — COMMENTED** [review]
- Was there a reason why the bars each have different meshes? Couldn't we make them use all the same bar and only apply different materials and textures? It would also make it easier to configure one prefab for it that has info like hand rotation, preview camera angle, etc.
- Depending on if we have a `MetalBar_Base` or something like that, I will think about the directory structure. Having the data folder on the same level as the 3 asset folders that need them could be improved. Iron can be in `Iron/Data`, Gold in `Gold/Data` etc. 
- I am not sure why the base game does it sometimes, but we are not going to suffix assets with _01. Sorry that I did not say this sooner. I can do the renaming work after we sorted out the thoughts above.

Unrelated
- With such big texture files, I think we might want to consider using git LSF @phumberdroz? The clone is 100MB for the source files in this PR alone.

**Comment by Kanf** [comment]
@Arkensor I made different meshes to add a little bit of variation, but I could change them to use the same mesh. It would take some time though, so maybe I could do optimisation pass later on? Right now I would prefer focusing on adding pickaxe.

**Comment by Arkensor** [comment]
#99 has some draft info for modeling guidelines, which is mostly covered by my comments below through.

As for the folder structure ... Do the base xobs for Ore, Nugget, and Ingot require a material, or do you intend to only use the xob mesh and apply materials in the .et prefabs? If the bases are standalone and need no Data folder, you could do `src/Assets/Props/Mining/MetalOre.xob`/`src/Assets/Props/Mining/MetalNugget.xob`/`src/Assets/Props/Mining/MetalBar.xob` and then have folders with the Materials and textures e.g. `src/Assets/Props/Mining/Gold/GoldOre.edds`/`src/Assets/Props/Mining/Copper/CopperNugget.emat`/`src/Assets/Props/Mining/Iron/IronBar.tiff`. And if we add more "retextures" to add more ores (which I do not think we will in the near future for the framework, but server owners likely will) they could be placed in `src/Assets/Props/Mining/NAME_OF_METAL/NAME_OF_METAL.fileextension`. 

As for the Prefabs, that is a bit more tricky. I think an argument can be made about the nuggets and bars being items, that cause storable in inventory? One option would be `src/Prefabs/Items/Mining/IronBar.et`/`src/Prefabs/Items/Mining/GoldNugget.et` etc. and the ore nodes go into `src/Prefabs/Mining/GoldOre.et` etc. But maybe you or someone else has a better idea to keep those 3 together in the prefabs, even though only 2/3 are real "items".

**Review by Arkensor — COMMENTED** [review]
Out of curiosity why did you prefix the texture files with `T_Resource_` instead of just calling it e.g. `Copper_BCR.edds`? Was it to distinguish between material and texture files?

I think there are some WIP leftovers in the PR:
- `src/Assets/Props/Mining/data/Resource_Gold.emat` is already present as `Gold.emat` in the "correct" folder I think? So i guess we could just delete `Resource_Gold.emat`?
- We have ores in `Prefabs/Items` and in `Prefabs/Ores`. The latter also still have _01 suffixes. Come to think about it, I think it might make sense if the ore prefabs stay under resources, since that is where server owners would look at when dragging farming prefabs into the world. Nuggets and bars can stay exactly where they are in items. Delete the current _01 files in `Prefabs/Resources/Ores` (assuming that they are not the updated new ones) and move the prefabs `CopperOre.et`, `GoldOre.et` and `IronOre.et` into `Prefabs/Resources/Ores` and then that should be flawless in my opinion. You might want to do this moving by placing them ingame in the world, and then drag them as "new" prefab from there so an updated .meta file is generated. If you move the files in windows explorer it will not update that. I can do this as well if you do not want to spend any more time on directory structure 😁

**Comment by KasperOnPC** [comment]
Looks like the prefabs are also missing the following components:
- ActionsManagerComponent (so they can be picked up) 
- InventoryItemComponent (so they can go in inventory)
- SoundComponent
- RigidBodyComponent

They can be easily modeled off the Apple if you want to DIY it @Kanf.

Alternatively, I'd be happy to make the changes after we have the assets merged in @Arkensor

**Comment by Kanf** [comment]
@KasperOnPC It must be a bug then, because I remember adding all of those components. I have even posted some screenshots when holding metal bars. 
Feel free to add them, I don't have a lot of time, and I want to finish pickaxe asap :)

**Comment by KasperOnPC** [comment]
> @KasperOnPC It must be a bug then, because I remember adding all of those components. I have even posted some screenshots when holding metal bars. 
> Feel free to add them, I don't have a lot of time, and I want to finish pickaxe asap :)

Ahh that's a shame. Really looking forward to having a pick axe!

**Pull request merged**
