### PR TITLE
Addition of sand gravel and cement gathering

### PR DESCRIPTION
**Pull request by KasperOnPC**
Sorry, @Arkensor I accidentally did the changes on main and wanted to work on some other stuff. 

Previous PR was #93 for everyone's context
The discussion was #90 

The last comment was from Ark:

>> But, one of the Sand Piles, for example, is just in a backyard. If we take this approach (of overriding every asset) it may limit where server owners can realistically place their "Glass Processors". If they place it wrong and don't think about the existing assets they could have 10 trucks pulling up at some random house in suburbia to load up on the sand.

> I understand, but I think this should be intended. If we have a resource that is practically everywhere on the map then that might not be a good idea for a high-value resource, but something like sand, for example, could just really be where ever you see it. Same as we do with apples right now. One has to keep in mind that if you want to avoid the usage of existing map objects that share the same prefab we could just have server owners remove balance destroying objects with a map utility to place down near it.

Okay, I'm fairly indifferent so what I will do is turn the Gravel & Sand piles into overrides and the Cement pile will be it's own prefab based on a dirt pile with its texture overridden, as it will be a slightly more valuable resource then gravel and sand. 

> What is the class name of the coca tree? I want to check how many there are and where they are placed.

It's called rosa_canina it looks like there are over 9,400 of them across the map.

### CODE REVIEW

**Comment by Arkensor** [comment]
Is this ready to go now?

**Comment by KasperOnPC** [comment]
Yup all good to go @Arkensor

**Review by Arkensor — COMMENTED** [review]
Looks good to me. I just have two thoughts you might want to adjust - or not.

1. The `Brick.et` is tiny in the inventory preview, I think you can move the camera closer in the item preview attributes. Also maybe you want to set up the brick so it can be held in your hands, check out the mining bars that I configured, they contain the minimal setup for it: [LINK](https://github.com/Kanf/EveronLife/blob/feature/mining_ores/src/Prefabs/Resources/Mining/IronBar.et)
2. I love the processing building, but I thought about maybe moving the place where you process stuff 
image Do you think that makes sense?

**Comment by KasperOnPC** [comment]
Thanks for the review @Arkensor, happy to make the changes. Please see the below:

- [ ] ItemPreview is an easy fix

- [ ] Hand translation seems to be a harder one? Any ideas here or is this fine?

**Player Perspective**
image

**Other Perspective**
image

- [ ] Move the processor action

I think it can be moved upstairs, I'm fine with that, but I do think it should be placed on a button as it is mechanically operated. I propose the button slightly to the right and above the current red circle.

**Comment by Arkensor** [comment]
We can put the interaction point on the controls desk as well sure 
image

About hand translation, well it is generally easy, this is just an attribute as the others. `InventoryItemComponent` > `Item Animation Attributes` > `Animation Attachments` > `Hand Additive ...`. After adjusting the values you must sadly restart workbench every time, but it takes maybe 5-8 attempts to make something half decent. Also if the bricks are too big by default you could consider scaling them down. We need to do our own prefab for this brick to change preview and handhold animation anyway, so might as well tweak that. Up to you :)

**Comment by Arkensor** [comment]
@KasperOnPC is this ready to be reviewed again? You can tell me more easily in the future by requesting a review again here:
image

**Comment by KasperOnPC** [comment]
Yeah sorry @Arkensor I'm not totally sold on my hand rotation but since I won't be able to get around to it for a little bit I think it's pretty good in it's current state.

**Review by Arkensor — APPROVED** [review]

**Pull request merged**
