### PR TITLE
Virtual quantities for items

### PR DESCRIPTION
**Pull request by Jacob-Mango**
Add quantity stacking system as part of Money System (see #9).

Prerequisites:
- The prefab has an `InventoryItemComponent`

Steps:
1. Open the prefab
2. Add the `EL_InventoryQuantityComponent` to the prefab under the entity
3. In the component, configure the maximum quantity that the entity can stack to
	[](https://i.imgur.com/KB18k0x.png)
4. Select the `InventoryItemComponent` and under the attributes open the `ItemPhysicalAttributes`
	[](https://i.imgur.com/ZfVyizo.png)
5. Set the `Size Setup Strategy` to `Volume` and the `Weight` and `Item Volume` to 0

Notes: 
- Items that use the component must be configured to have no weight

### CODE REVIEW

**Comment by Arkensor** [comment]
Before looking at the code, here are some general remarks after playtesting:
1. Taking a stacked item from the ground to inventory does not try to stack it on the first available item in the inventory
2. Right-click to move to a stack on the ground keeps them separate instead of trying to merge it with an available stack in the vicinity. Yes, I know you can manually merge them together afterward.
3. Stacks created on split are duplicated in SP/Workbench
4. Is there an ability to configure unlimited stack sizes? Or do you just plan to use -1 for that?
5. We should see how much quantity can be displayed in the GUI without overlap. Maybe above `999` we want to start using stuff like `1.2k` for 1203? So `n / 1000` round to one decimal?

**Comment by Jacob-Mango** [comment]
> Taking a stacked item from the ground to inventory does not try to stack it on the first available item in the inventory

How was this performed? Through an action or dragging the item to which part of your screen? Or was it another method? It does appear to be not intentional.

> Right-click to move to a stack on the ground keeps them separate instead of trying to merge it with an available stack in the vicinity. Yes, I know you can manually merge them together afterward.

I don't believe we should change this behaviour and it should remain as is. If they want to combine they can combine them while they are on the ground. Does anyone else have any thoughts on this?

> Stacks created on split are duplicated in SP/Workbench

Hopefully just have to check the authority for that one

> Is there an ability to configure unlimited stack sizes? Or do you just plan to use -1 for that?

Currently no. I will make it so any negative value means unlimited

> We should see how much quantity can be displayed in the GUI without overlap. Maybe above 999 we want to start using stuff like 1.2k for 1203? So n / 1000 round to one decimal?

Overriding the vanilla layout. Fun times :D Maybe the game already handles this? Otherwise it shouldn't be too hard to add. Will investigate.

**Comment by Arkensor** [comment]
> How was this performed? Through an action or dragging the item to which part of your screen? Or was it another method? It does appear to be not intentional.

You just right-click items to pick them up from the ground but they do not join any stack. Instead, the real item with its quantity is picked up. I think there might just be no code that attemtps to merge it first.

> Overriding the vanilla layout. Fun times :D Maybe the game already handles this? Otherwise it shouldn't be too hard to add. Will investigate.

No, I am not saying override. We set the text manually don't we? In the inventoryUI it's just a text widget that displays the stack size. Instead of setting x = "1000" we do x = "1k" and it should work just fine.

**Comment by KasperOnPC** [comment]
Just before getting into feedback, I wanted to thank you @Jacob-Mango for taking this head-on. It’s obviously a super important but less ‘flashy’ part of the mod that acts as a foundation for everything else and a feature that players will use more than any other. 

**Splitting Stacks seems to create more items?**
I assume this is unintended and simply a bug.
Creates another apple

**Splitting Stacks from vicinity goes into inventory** 
This is interesting, happy to be told I’m wrong here. But if you split an item on the floor / in the vicinity, shouldn’t the split stack also be on the floor rather than in your inventory? 
Splits into player inventory

**Keybind Ctrl + Right Click**
Is there any reason this can’t be Ctrl + Left Click? It seems natural as you use left click to drag items, therefore it’s used to combine stacks so it would be more intuitive to use left click if possible IMO.

Potentially, a better key bind might even be Shift + Left Click. That is what they do in World of Warcraft where players have to do a lot of inventory management.

**Gathering into existing stacks**
I noticed as you gather apples each one creates a new stack and then goes into an existing one. Maybe there’s a way it could work where specifically for gathering it goes into an existing stack if possible?
Gathering Doesn't Stack
This seems to work fine when I pick up apples off the table, just not gathering. 

**Auto-stacking Feedback**
> I don't believe we should change this behavior and it should remain as is. If they want to combine they can combine them while they are on the ground. Does anyone else have any thoughts on this?

There are Pros and Cons for both approaches but I also think this should remain unchanged. The two primary reasons are consistency (stacks are kept the same and work the same in the vicinity and in inventory) and also so players can prepare/split up items for a group (like distributing their food to friends, without each other player having to split it). 

The second point would also work seamlessly for traders. An example is someone who goes to a trader and buys 4 x 4 stacks of magazines for their 4 friends. When they meet up they can simply drop the stacks on the ground, if they just wanted one stack of 16, they could have just bought 1 x 16 magazines and dropped it on the ground as a single stack. If it automatically merged them it would cause each player to do more inventory management. See #8.

**Other RPG Example UIs**
I thought an example from a more recent RPG might be good to have in this thread. I think New World’s stack splitting is probably the best I have seen. You can input the size of the new stack, it defaults to splitting the stack in half and there is also a slider where you can select the quantity. The quantity of the existing stack is also shown, but I do like the way yours works @Jacob-Mango, particularly how it allows you to quickly split a stack into 4, rather than having to do a double split.  

From New World
image

**Comment by Arkensor** [comment]
1. This happens when I right-click and want to move a full stack to the ground. Inventory stack size becomes 0 and the below error appears
image

2. The pickup logic is inconsistent. When I right-click a single apple it adds it to the first available stack. If I pick up two stacked apples and they can be combined with a different stack completely they are combined. If I pick up 3 apples and my inventory as a stack of 3, I get two separate stacks with 3, instead of one with 4 and one with 2. Either we combine stacks on pickup or we don't. But it would be kind of lame if you had 5 stacks of a single apple in your inventory when picking up individual apples that layed around. So I would say we always combine stacks on pickup.

**Comment by Arkensor** [comment]
Closed by #179

**Pull request closed without merging**
