### PR TITLE
Debug World fixed

### PR DESCRIPTION
**Pull request by Tomboru**
Hi there, with this pull request the debug world is fixed.
What do I mean with fixed?

- [X] Missing collisions are there again
- [X] Axe prefab is fixed (Invisble because of missing component)
- [X] Props like Apple Juicer, trees, etc are usable again
- [X] Car prefab is fixed (With it now a car with license plate spawns)
- [X] All layers are renewed, so everything has it's own "station"

### CODE REVIEW

**Comment by Tomboru** [comment]
Okay noticed a weird behaivour.
Collisions work for half of the map.
The other half doesn't - but works again if just all entities are moved into another layer.
But after game restart it misses again collisions.

Couldn't figure out why.
Already tried to replace each entity, etc.
Worked for the session, but after that stopped working.

Also tryed to copy entities from tomato station which doesn't have this anomaly.
But even this entity stops working after restart.

**Review by TheFreaks-dev — COMMENTED** [review]
Very good

**Review by Pyravlon — APPROVED** [review]
Seems really nice ^^

**Comment by Tomboru** [comment]
> Seems really nice ^^

Right now I'm still trying to fix one thing. (The collisions are still halfway broken and I can't find out why)

**Comment by Pyravlon** [comment]
> > Seems really nice ^^
> 
> Right now I'm still trying to fix one thing. (The collisions are still halfway broken and I can't find out why)

Yeah, I can't figure out what the source of this issue is and why cutting and pasting fixes collisions.

**Comment by Tomboru** [comment]
Alright found the problem why collisions don't work and also why many other problems occure.
In short -> The Debug world is completely destroyed (I will push a completely new one)

**Comment by jasper-one** [comment]
@Tomboru I see the problem with the Axe is universal when I bring it into a mod that has this as a dependency do you still plan to bring in a new debug?

Would love to see this PR killed and a new one if you do, even just for the Axe fix

**Comment by jasper-one** [comment]
Closing as merged in Dev

**Pull request closed without merging**
