### PR TITLE
Add water bottle item

### PR DESCRIPTION
**Pull request by Arkensor**
WIP Water bottle. I wanted to rotate them so you can see the label, but I got no idea how that works. Any time I want to adjust angles they just randomly do not work.

image

Also for some reason while inside the inventory it looks bugged. All of the currently added items have these issues.
image

### CODE REVIEW

**Comment by 12gabriel3** [comment]
I had some problems as well, I could work around them by saving and reloading the prefab, otherwise the rotations would randomly not apply.

image

The angles for this result are these
image

**Comment by PackJC** [comment]
@12gabriel3 Same issue within my minnow. I apply hand additive rotation and sometimes it doesn't apply.

**Comment by 12gabriel3** [comment]
> @12gabriel3 Same issue within my minnow. I apply hand additive rotation and sometimes it doesn't apply.

Make sure you are editing your prefab and your entity instance is not overriding the values of the prefab.

**Comment by Arkensor** [comment]
The issue with the in-hand preview on the inventory screen is a known issue and has been reported to BI. Using hand additive is the correct way for now until we have custom animation setups for each item.

**Pull request merged**
