### PR TITLE
Redesign of HUD

### PR DESCRIPTION
**Pull request by LuxPoseidon**
HUD redesign to match the game, changes color of inner sections, White -> Yellow -> Red.
image

### CODE REVIEW

**Comment by LuxPoseidon** [comment]
Additional note, there is customization in the BetaHud.c file, Config integration is the next step for the customizability.

**Comment by LuxPoseidon** [comment]
@Arkensor

**Review by Arkensor — COMMENTED** [review]
Technical note: You could try making the image files `.tiff` instead of `.png` for better compression maybe. See if that makes a difference.

The cup icon is somewhat breaking the full height deisgn of the others because it ends half way to have the cup plate below that. It is not something I worry about it too much right now and I also have no better GUI design ideas in mind at the moment, but maybe in the future this could be tweaked.

I also saw you scrapped the idea of a stamina bar? Maybe we could have both present, a bar and an icon, and depending on a setting it shows either one. Not sure.

**Comment by LuxPoseidon** [comment]
> 

Yea the bar is toggleable. bool variable in the code for it.

For performance ya could try that file type. I see what you mean with the cup as well.

**Pull request merged**
