### PR TITLE
Feature | Rowan Berries 🍒🍒🍒

### PR DESCRIPTION
**Pull request by SaxW**
@Arkensor created a fresh branch and fork (cleaning my end up)
following your coments from: https://github.com/EveronLife/EveronLife/pull/94

**Resolved?**
- [x]  What is the DefaultMaterial_2D_View?
- [x]  What are these berries? Maybe we can give them a more specific name? If not at least we need to fix the capitalization of the assets e.g. Berries.xob
- [x]  The asset is quite big still, especially the texture. Maybe @12gabriel3 has some tips on how to get this asset smaller?
- [x]  You accidentally committed lots of changes regarding plums. Both assets and on the map. I think for this PR you should only add the berry asset and not change anything else.

### CODE REVIEW

**Comment by SaxW** [comment]
@Arkensor created a fresh branch and fork (cleaning my end up)
following your coments from: https://github.com/EveronLife/EveronLife/pull/94

**Resolved?**
- [ ]  What is the DefaultMaterial_2D_View?
- [ ]  What are these berries? Maybe we can give them a more specific name? If not at least we need to fix the capitalization of the assets e.g. Berries.xob
- [ ]  The asset is quite big still, especially the texture. Maybe @12gabriel3 has some tips on how to get this asset smaller?
- [ ]  You accidentally committed lots of changes regarding plums. Both assets and on the map. I think for this PR you should only add the berry asset and not change anything else.

**Comment by SaxW** [comment]
Regarding asset, it's 48KB for the .fbx + 68KB for the tiff.

**Review by thebonbon — APPROVED** [review]

**Review by Arkensor — COMMENTED** [review]
Much better in file size. On a general note, why are we importing rowan berries? They are not eatable by humans so I question their gameplay use? What exactly is this for?

Regardless, there are a few [modeling guideline convention](https://github.com/EveronLife/EveronLife/discussions/99#discussioncomment-2932302) problems: 
- File names are not CamelCase. No spaces allowed. Name should be `RowanBerries.xyz`
- File extensions must be upper case e.g. `_BCR.tiff`
- Lowercase `data` should be `Data`

**Comment by SaxW** [comment]
@Arkensor this follows https://github.com/EveronLife/EveronLife/pull/50

The existing berry tree prefab in the game is a Rowan tree. 

Had a look at it seems these berries are edible, but may cause stomach aches if eaten raw so they're cooked before consumption.

Will look at the convention issues later today.

**Comment by Arkensor** [comment]
> The existing berry tree prefab in the game is a Rowan tree.

Alright, then that is ok. We just need to find a good RP use for it then. Maybe you can check what kind of products are made from them :=)

**Comment by KasperOnPC** [comment]
From Wikipedia:
> Fresh fruit are usually not tasty, but they can be debittered and made into compote, jelly, jam, a tangy syrup, a tart chutney, or juice, as well as wine and liqueur, or used for tea or to make flour.

So maybe they can't be consumed directly but can be processed into Jam or used in Wine production

**Review by Arkensor — CHANGES_REQUESTED** [review]
There is still an outdated `Rowan Berries.emat` and `Rowan Berries.et` files that need name convention fixing, but apart from that yes, sounds like a useful resource we could use for various processing.

**Comment by SaxW** [comment]
updated @Arkensor

**Review by Arkensor — APPROVED** [review]

**Pull request merged**
