### PR TITLE
Add editable eden world

### PR DESCRIPTION
**Pull request by Thesam1798**
The purpose of this Merge Request is to be able to modify the buildings and resources present in Eden

I did it in several steps, copy the base map (eden), put it in the same directory to overload it, then add the GameMode and the SpwanPoint, then re-import the StPhillipe samples, for that I created prefabs of the existing ones to copy them more simply.

### CODE REVIEW

**Comment by Arkensor** [comment]
AR intentionally does not support editing parent scenes. Essentially reuploading the entire map is not really an option, unless I am missing something. From my understanding, all future game updates would automatically create a merge conflict with change done to the map files, leaving only the option to manually re-implement customizations. 
More importantly, it would instantly increase the framework size by 125mb.

The alternative way to do smaller edits to the map is to do it like in Arma 3. Hide objects via script and spawn anything in the child scene you need. We intend to make removing objects as simple as placing down a remove utility object in the child scene and then maybe selecting which objects to remove or automatically remove all in a bbox or radius.

Did you see any problems with scripted map manipulation which lead you to make a full copy or what were your reasons for it? Is there some advantage I am not aware of?

**Comment by Thesam1798** [comment]
This is not a copy of the whole scene, this is just a reference to the prefab.

This was my basic assumption on Arma4Dev, but it is impossible in the current context of AR because it is a parent scene.

I tried several days without succeeding to delete an object without its ID present in the current scene and no way to recover the parent scene, then it is possible that I forgot something

**Comment by Arkensor** [comment]
> This is not a copy of the whole scene, this is just a reference to the prefab.

Reference for prefab? Can you explain that a bit more? What is it that you can do when adding the files like this? Does this help to remove objects from the Everon map? If so how?

**Comment by Thesam1798** [comment]
The .layer files are just a relation between the AR prefab and the position.

If the prefab is updated by BI Studio it will be automatically updated in the map, but if an update is done by BI directly on the map, like a move or an addition it will not be taken into account.

I'm currently working on another solution as proposed in arma 3, but it seems to me more expensive in "run time" resources than override the map

**Review by ThibaudetTevai — APPROVED** [review]

**Comment by LuxPoseidon** [comment]
I do agree that having an editable version would be great, to do this however I agree with Ark, "referencing" the existing prefab probably isn't the way, a renamed standalone copy "Life.Everon"  or something would be better, no links to existing map, its own map copy.

**Comment by thebonbon** [comment]
> ... Hence I would close this PR. The object removal map utility would be subject to a [discussion](https://github.com/EveronLife/EveronLife/discussions/new?category=ideas) first. 
>
Agreed

**Pull request closed without merging**
