### PR TITLE
Add Fish Models

### PR DESCRIPTION
**Pull request by PackJC**
This is a minnow that can be used to implement fishing as was discussed in #82.

The model is 34 kB and the .edds is 145 kB. The face count is 1563. 
I created the model from the open source texture using Blender. 
This is the texture I used for this model. https://commons.wikimedia.org/wiki/File:Pimephales_promelas.jpg

image

In-game I am using the Map hand animation. 
unknown

The next steps following the addition of this model is to identify a way to harvest from a water source while holding an item.

### CODE REVIEW

**Comment by Arkensor** [comment]
- The file size for one single fish is way too big. We will need to reduce this. I will try and get the modeling guidelines pushed next week, so you have some numbers to work with.
- I do not think an extra preview.png will be needed.

**Comment by PackJC** [comment]
@Arkensor Thank you for reviewing, I will adjust as needed in the coming days. :)

**Comment by Arkensor** [comment]
@PackJC Also see #99 for reference until we have a separate page on it

**Comment by PackJC** [comment]
Items adjusted and proper naming conventions used

**Review by ThibaudetTevai — APPROVED** [review]

**Review by ThibaudetTevai — APPROVED** [review]

**Comment by Arkensor** [comment]
I think it will be best for this to be merged as one big `feature/fishing` with fishing poles, animations, etc. There is not really much we can do with just the fish model at the moment. So for now I would close this PR and you keep working until you got the whole system ready?

**Pull request closed without merging**
